# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

# The name of this app. Must be unique within a project.
name: flask

# The runtime the application uses.
type: "python:3.9"

variables:
    env:
        PACKAGE_MANAGER: pipenv
        PIP_VERSION: 22.0.4
        PIPENV_VERSION_BUILD: 2022.4.21
        POETRY_VERSION: 1.1.13
        POETRY_VIRTUALENVS_IN_PROJECT: true
        POETRY_VIRTUALENVS_CREATE: false

hooks:
    build: |
        set -e
        # export Flask app for Blackfire
        export FLASK_APP=server.py
        # Setup pip.
        python -m pip install pip==$PIP_VERSION
        
        # Install pipenv.
        pip install pipenv==$PIPENV_VERSION_BUILD
        # Check and verify the lockfile. Track failures.
        pipenv check && pipenv verify && pipenv --support > pipenv.support
        # Install dependencies to the virtual environment.
        VENV_VERSION=$(python3 -c 'import sys; print(".".join(map(str, sys.version_info[:3])))')
        pipenv --python $VENV_VERSION
        pipenv install --deploy

web:
    # Commands are run once after deployment to start the application process.
    commands:
        start: blackfire-python flask run -p $PORT