# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

# The name of this app. Must be unique within a project.
name: flask

# The runtime the application uses.
type: "python:3.9"

variables:
    env:
        PACKAGE_MANAGER: pipenv
        PIP_VERSION: 22.0.4
        PIPENV_VERSION_BUILD: 2022.4.21

hooks:
    build: |
        set -e
        export FLASK_APP=server.py
        python -m pip install pip
        pip install -r requirements.txt


web:
    # Commands are run once after deployment to start the application process.
    commands:
        start: flask run -p $PORT